apiVersion: batch/v1
kind: Job
metadata:
  name: load-tester
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: load-tester
      labels:
        app: example-app
        task: load-generator
    spec:
      containers:
      - name: ab
        resources:
          requests:
            memory: "1Gi"
            cpu: 1
        image: hub.comcast.net/k8s-eng/ab
        args: ["-c 1","-r","-s 5000000","-n 10","http://10.131.153.123:8080/"]
      restartPolicy: Never
