apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: udp-test
  name: udp-test
  namespace: udp-test
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: udp-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: udp-test
    spec:
      containers:
      - image: abgordon/udp-server:0.0.1
        imagePullPolicy: IfNotPresent
        name: udp-test
        ports:
        - containerPort: 8085
          protocol: UDP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
