apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-12-11T20:38:22Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2021-02-06T01:05:00Z"
  generateName: lbtestserver-121-67db6dbc68-
  labels:
    pod-template-hash: 67db6dbc68
    run: lbtestserver-121
  name: lbtestserver-121-67db6dbc68-nc26d
  namespace: lb-test-andrew
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: lbtestserver-121-67db6dbc68
    uid: 53c76356-5e97-40ee-a20a-f58a86654ee5
  resourceVersion: "136813646"
  selfLink: /api/v1/namespaces/lb-test-andrew/pods/lbtestserver-121-67db6dbc68-nc26d
  uid: 19c7c24b-c5b9-4e55-a4d3-ae463918a6e0
spec:
  containers:
  - image: registry.vipertv.net/arbuckle-hacks/lbtestserver:1.2
    imagePullPolicy: IfNotPresent
    name: lbtestserver-121
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hnh4h
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 10.131.153.80
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-hnh4h
    secret:
      defaultMode: 420
      secretName: default-token-hnh4h
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-12-11T20:38:22Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-12-12T01:28:35Z"
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-12-11T22:04:14Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-12-11T20:38:22Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://3d092e9ef7c27d829313700d9f30c02a00171953f26b201d4bc7e8683b5be369
    image: registry.vipertv.net/arbuckle-hacks/lbtestserver:1.2
    imageID: docker-pullable://registry.vipertv.net/arbuckle-hacks/lbtestserver@sha256:7eb12cf55e587ada86adc5c4206bd1dec61af8fe332446f6dcf4644f646e598e
    lastState: {}
    name: lbtestserver-121
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-12-11T22:04:13Z"
  hostIP: 10.131.153.80
  phase: Running
  podIP: 192.168.44.37
  podIPs:
  - ip: 192.168.44.37
  qosClass: Guaranteed
  startTime: "2020-12-11T20:38:22Z"
